name: Proyecto1_Equipo9

on:
  push:
    branches:
      - main

jobs:
  supertest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
            node-version: '20'
      - name: Iniciar nodejs
        run: npm ci
      - name: Tests (Supertest)
        run: npm run test

  eslint:
    needs: supertest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
            node-version: '20'
      - name: Iniciar nodejs
        run: npm ci
      - name: Tests (Eslint)
        run: npm run lint

  snyk:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
            node-version: '20'
      - name: Iniciar nodejs
        run: npm ci
      - name: Tests (Snyk)
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: npm run snyk-test

  dockerbuild-trivy-pushimagetoecr:
    needs: snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build (dockerimage)
        run: docker build --provenance false -t proyecto1_grupo9:latest .
      
      - name: Trivy - Generar SBOM
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: proyecto1_grupo9:latest
          format: cyclonedx
          output: sbom.json
      
      - name: Trivy (SUBIR INFORME)
        uses: actions/upload-artifact@v4
        with: 
            name: sbom-trivy
            path: sbom.json 

      - name: AWS (CONFIGURE)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}     

      - name: AWS (LOGIN)
        uses: aws-actions/amazon-ecr-login@v2

      - name: AWS (TAG IMAGE)
        run:  docker tag proyecto1_grupo9:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest 

      - name: AWS (PUSH IMAGE)
        run:  docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest 